### ISSUE TITLE
[Feature Request] redux-toolkit 세팅

### ISSUE THREAD

**Issue by jma1020** [TRIPONG-2022/frontend#30]
# Feature Request

redux-toolkit 세팅

## Description

전역상태관리를 사용할 수 있도록 redux-toolkit세팅
SSG와  SSR을 고려한 세팅

## ToDo

- [x] redux-toolkit에 필요한 세팅
- [x] 세팅을 확인하기 위한 test페이지
- [x]  SSR, SSG에서 redux 접근을 위한 next-redux-wrapper 설정
