### ISSUE TITLE
[Feature Request] OAuth 연결 체크

### ISSUE THREAD

**Issue by jma1020** [TRIPONG-2022/frontend#39]
# Feature Request

OAuth 연결 체크

## Description

OAuth 로그인 시 페이지 이동 확인, Cookie와 response 데이터 유무 확인

## ToDo

- [x] OAuth 버튼 클릭 시 로그인 체크
- [x] 받아오는 Cookie 확인
- [x] response 데이터 확인
- [x] 추후 flow 고민
