### ISSUE TITLE
[Feature Request] 포스트 페이지 구현

### ISSUE THREAD

**Issue by sangrimlee** [TRIPONG-2022/frontend#52]
# Feature Request

포스트 페이지 구현

## Description

- 작성된 포스트에 대한 페이지 구현

## ToDo

- [x] 포스트 페이지 구현
- [x] 포스트 페이지를 SSR로 구현
- [x] 포스트 페이지의 레이아웃 구현
