### ISSUE TITLE
[Feature Request] 포스트 관련 검색 기능

### ISSUE THREAD

**Issue by sangrimlee** [TRIPONG-2022/frontend#63]
# Feature Request

GNB 에 들어가는 Search Bar 를 생성 및 기능 추가

## Description

GNB 에 들어가는 Search Bar 를 생성 및 기능 추가

## ToDo

- [x] portal 을 이용한 SearchBar 렌더링
- [x] Search Bar 스타일링
- [x] Search redirect 코드 추가
